### PR TITLE
🍰 PR template - discussion

### PR DESCRIPTION
**Pull request by ulfgebhardt**
## 🍰 Pullrequest

This is a template for PRs. I want to discuss wether this is missing something important, requires changes, etc.

If everyone agrees on a PR-Template like this one I would open an PR on a core Repo of your choice to be merged there and backported to the other repos.

This PR is made in the template style provided by this PR.
See how it would look when making a new PR [here](https://github.com/cmangos/issues/blob/ff6c97023fe7e0273ee2d99b3a199aed284d9ac2/.github/PULL_REQUEST_TEMPLATE.md)

### Proof

- https://blog.theodo.fr/2016/05/increase-team-productivity-with-github-templates/
- https://seesparkbox.com/foundry/better_pull_requests_merge_requests_with_templates

### Issues

- relates to `Utilize Github Templates for Issue prefiltering` https://github.com/cmangos/issues/pull/1759
- relates to `GitHub issue templates - adjustments` https://github.com/cmangos/issues/pull/1909

### How2Test

- This PR reassembles the given PR-Template
- See how it would look when making a new PR [here](https://github.com/cmangos/issues/blob/ff6c97023fe7e0273ee2d99b3a199aed284d9ac2/.github/PULL_REQUEST_TEMPLATE.md)

### Todo / Checklist

- [ ] Everyone agrees
- [ ] Port to all core repo @Muehe

### CODE REVIEW

**Comment by AnonXS** [comment]
please no checkbox for sources...
checkbox are for t a s k s

**Comment by jimmybrancaccio** [comment]
Looks nice, one spelling mistake:

`<!-- Link ressources as proof -->`

should be:

`<!-- Link resources as proof -->`

Nice work overall!

**Comment by ulfgebhardt** [comment]
@jimmybrancaccio Fixed it. Would you mind merging it?
Also: Which Repo should I open the PR for the template? vanilla, tbc or wotlk? Or should it be all?

**Comment by jimmybrancaccio** [comment]
@ulfgebhardt Awesome, thanks. I think we should submit this PR to all repos because each one should (as far as I know) accept PRs from the public.

Before I merge though, I would like to get the input of more devs - as they're the ones who handle merging PRs into master.

Tagging a couple devs (it would be awesome if we had a team on here so I could tag the team! 😄) - @cyberium @cala @Tobschinski @killerwife @Warlockbugs @Saltgurka @MantisLord @Laizerox I dunno why I can't Grz3s :'(

**Comment by Muehe** [comment]
I can take care of the merge, no need to create more PRs.

On topic, I think the "Checklist" and "Todo" sections are kind of redundant.

**Comment by ulfgebhardt** [comment]
@Muehe <3

**Comment by ulfgebhardt** [comment]
@Muehe Can I assist you on anything before mergin this?

**Comment by jimmybrancaccio** [comment]
One question for @Muehe - why do you think the checklist/todo is redundant?

Looks good to me 👍

**Comment by ulfgebhardt** [comment]
It was to separate headings before - i already corrected that @jimmybrancaccio

**Comment by Muehe** [comment]
@jimmybrancaccio Checklist/Todo were two separate sections before, but that has been changed since I made the comment.

Core PR is merged.

@cala @killerwife @Grz3s If you want the PR template in the DB repos cherry-pick [0272fdf7187ae03883eb63c84527fed256152021](https://github.com/cmangos/mangos-classic/commit/0272fdf7187ae03883eb63c84527fed256152021), I don't have commit rights.

**Pull request merged**
